[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "select"
rule = ["[]REJECT"]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯æµ‹é€Ÿ", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯æ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯æµ‹é€Ÿ"
type = "url-test"
rule = ["(æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯æ‰‹åŠ¨"
type = "select"
rule = ["(æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬æµ‹é€Ÿ", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬æµ‹é€Ÿ"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ‰‹åŠ¨"
type = "select"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡ºğŸ‡² ç¾å›½æµ‹é€Ÿ", "[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½æµ‹é€Ÿ"
type = "url-test"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨"
type = "select"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡¨ğŸ‡³ å°æ¹¾æµ‹é€Ÿ", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾æ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾æµ‹é€Ÿ"
type = "url-test"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾æ‰‹åŠ¨"
type = "select"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡¸ğŸ‡¬ ç‹®åŸæµ‹é€Ÿ", "ğŸ‡¸ğŸ‡¬ ç‹®åŸæ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸæµ‹é€Ÿ"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸæ‰‹åŠ¨"
type = "select"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "select"
rule = ["[]ğŸ‡°ğŸ‡· éŸ©å›½æµ‹é€Ÿ", "[]ğŸ‡°ğŸ‡· éŸ©å›½æ‰‹åŠ¨"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½æµ‹é€Ÿ"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½æ‰‹åŠ¨"
type = "select"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
