[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "config/self_block.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "config/self_proxy.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "acl4ssr/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "config/self_direct.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "acl4ssr/BanAD.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "acl4ssr/BanEasyList.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "acl4ssr/BanEasyListChina.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "acl4ssr/BanEasyPrivacy.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "acl4ssr/BanProgramAD.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/GoogleCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/Ruleset/SteamCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/ChinaIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "acl4ssr/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,LAN"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
